volumes:
  postgres-data:

services:
  app:
    image: mikoto2000/tauri2
    volumes:
      - .:/workspaces:bind
    env_file:
        - .env
    command: sleep infinity
    network_mode: service:db
  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"
    env_file:
        - .env
